# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    users_img_directory: '%kernel.project_dir%/public/user/img'
    formations_img_directory: '%kernel.project_dir%/public/formations/img'
    cours_img_directory: '%kernel.project_dir%/public/cours/img'
    cours_video_directory: '%kernel.project_dir%/public/cours/video'
    events_img_directory: '%kernel.project_dir%/public/evenements/img'
    formations_qr_code_directory: '%kernel.project_dir%/public/formations/qr_codes'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
